camera:
  ros__parameters:
    port: 5600

qualisys_mocap:
  ros__parameters:
    ip: "192.168.0.0"
    port: 22223
    version: "1.22"
    body: "bluerov"

qualisys_localizer:
  ros__parameters:
    body: "bluerov" # This should be the same as the body parameter setting for the qualisys_mocap node

gazebo_localizer:
  ros__parameters:
    gazebo_odom_topic: "/model/bluerov2_heavy/odometry"
